In [1]:
import pandas as pd

*1. Carreguem les dades*

In [2]:
df_wines = pd.read_csv("winemag-data-130k-v2.csv")
df_wines.drop("Unnamed: 0", axis = 1, inplace = True)
df_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [3]:
df_countries = pd.read_csv("country-codes_csv.csv")
df_countries

,FIFA,Dial,ISO3166-1-Alpha-3,MARC,is_independent,ISO3166-1-numeric,GAUL,FIPS,WMO,ISO3166-1-Alpha-2,...,Sub-region Name,official_name_ru,Global Name,Capital,Continent,TLD,Languages,Geoname ID,CLDR display name,EDGAR
0,TPE,886,TWN,ch,Yes,158.0,925,TW,NaN,TW,...,NaN,NaN,NaN,Taipei,AS,.tw,"zh-TW,zh,nan,hak",1668284.0,Taiwan,NaN
1,AFG,93,AFG,af,Yes,4.0,1,AF,AF,AF,...,Southern Asia,Афганистан,World,Kabul,AS,.af,"fa-AF,ps,uz-AF,tk",1149361.0,Afghanistan,B2
2,ALB,355,ALB,aa,Yes,8.0,3,AL,AB,AL,...,Southern Europe,Албания,World,Tirana,EU,.al,"sq,el",783754.0,Albania,B3
3,ALG,213,DZA,ae,Yes,12.0,4,AG,AL,DZ,...,Northern Africa,Алжир,World,Algiers,AF,.dz,ar-DZ,2589581.0,Algeria,B4
4,ASA,1-684,ASM,as,Territory of US,16.0,5,AQ,NaN,AS,...,Polynesia,Американское Самоа,World,Pago Pago,OC,.as,"en-AS,sm,to",5880801.0,American Samoa,B5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SAH,212,ESH,ss,In contention,732.0,268,WI,NaN,EH,...,Northern Africa,Западная Сахара,World,El-Aaiun,AF,.eh,"ar,mey",2461445.0,Western Sahara,U5
246,YEM,967,YEM,ye,Yes,887.0,269,YM,YE,YE,...,Western Asia,Йемен,World,Sanaa,AS,.ye,ar-YE,69543.0,Yemen,T7
247,ZAM,260,ZMB,za,Yes,894.0,270,ZA,ZB,ZM,...,Sub-Saharan Africa,Замбия,World,Lusaka,AF,.zm,"en-ZM,bem,loz,lun,lue,ny,toi",895949.0,Zambia,Y4
248,ZIM,263,ZWE,rh,Yes,716.0,271,ZI,ZW,ZW,...,Sub-Saharan Africa,Зимбабве,World,Harare,AF,.zw,"en-ZW,sn,nr,nd",878675.0,Zimbabwe,Y5
249,ALD,358,ALA,NaN,Part of FI,248.0,1242,NaN,NaN,AX,...,Northern Europe,Аландские острова,World,Mariehamn,EU,.ax,sv-AX,661882.0,Åland Islands,NaN

In [4]:
# Filtrem el dataset de countries per aquelles columnes interesants per a l'anàlisis
df_countries = df_countries[["official_name_en", "Region Name", "Sub-region Name", "Developed / Developing Countries"]]
# df_countries = df_countries.loc[~df_countries["official_name_en"].isnull()]
df_countries

,official_name_en,Region Name,Sub-region Name,Developed / Developing Countries
0,NaN,NaN,NaN,NaN
1,Afghanistan,Asia,Southern Asia,Developing
2,Albania,Europe,Southern Europe,Developed
3,Algeria,Africa,Northern Africa,Developing
4,American Samoa,Oceania,Polynesia,Developing
...,...,...,...,...
245,Western Sahara,Africa,Northern Africa,Developing
246,Yemen,Asia,Western Asia,Developing
247,Zambia,Africa,Sub-Saharan Africa,Developing
248,Zimbabwe,Africa,Sub-Saharan Africa,Developing
249,Åland Islands,Europe,Northern Europe,Developed

*2. Unim els dos datasets*

In [5]:
# S'ha detectat que alguns noms de països no estan escrits de la mateixa manera, per tant, caldrà homogeneïtzar els valors
countries_b = set(df_countries["official_name_en"].unique())
countries_a = set(df_wines["country"].unique())
countries_a - countries_b

{'Czech Republic', 'England', 'Macedonia', 'Moldova', 'US'}

In [6]:
replace_dict = {"Czechia" : "Czech Republic",
                "United Kingdom of Great Britain and Northern Ireland" : "England",
                "The former Yugoslav Republic of Macedonia" : "Macedonia",
                "Republic of Moldova" : "Moldova",
                "United States of America" : "US"}
df_countries.loc[df_countries['official_name_en'].isin(replace_dict.keys()), 'official_name_en'] = df_countries['official_name_en'].map(replace_dict)
df_countries['official_name_en']

C:\Users\mbmiq\AppData\Local\Temp\ipykernel_11324\1348248936.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_countries.loc[df_countries['official_name_en'].isin(replace_dict.keys()), 'official_name_en'] = df_countries['official_name_en'].map(replace_dict)

0                 NaN
1         Afghanistan
2             Albania
3             Algeria
4      American Samoa
            ...
245    Western Sahara
246             Yemen
247            Zambia
248          Zimbabwe
249     Åland Islands
Name: official_name_en, Length: 250, dtype: object

In [7]:
df_wines_merged = pd.merge(df_wines, df_countries, how="left", left_on = ["country"], right_on = ["official_name_en"])
df_wines_merged

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,official_name_en,Region Name,Sub-region Name,Developed / Developing Countries
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Italy,Europe,Southern Europe,Developed
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Portugal,Europe,Southern Europe,Developed
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,US,Americas,Northern America,Developed
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,US,Americas,Northern America,Developed
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,US,Americas,Northern America,Developed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),Germany,Europe,Western Europe,Developed
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,US,Americas,Northern America,Developed
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,France,Europe,Western Europe,Developed
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,France,Europe,Western Europe,Developed
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,France,Europe,Western Europe,Developed

*3. Descripció de les dades*

In [8]:
df_wines_merged.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [9]:
df_wines_merged["points"].value_counts(dropna=False)

points
88     17207
87     16933
90     15410
86     12600
89     12226
91     11359
92      9613
85      9530
93      6489
84      6480
94      3758
83      3025
82      1836
95      1535
81       692
96       523
80       397
97       229
98        77
99        33
100       19
Name: count, dtype: int64

In [10]:
df_wines_merged["price"].value_counts(dropna=False)

price
NaN      8996
20.0     6940
15.0     6066
25.0     5805
30.0     4951
         ...
451.0       1
574.0       1
764.0       1
319.0       1
848.0       1
Name: count, Length: 391, dtype: int64

In [11]:
# La variable "country" és molt important perquè ens permet fer el merge amb l'altre dataset
# per tant eliminarem aquelles mostres que tinguin valor null
df_wines_merged["country"].isnull().value_counts(dropna=False)

country
False    129908
True         63
Name: count, dtype: int64

In [12]:
df_wines_merged = df_wines_merged.loc[~df_wines_merged["country"].isnull()]

In [13]:
# Descripció de les variables categòriques
df_wines_merged.describe(include='O')

,country,description,designation,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,official_name_en,Region Name,Sub-region Name,Developed / Developing Countries
count,129908,129908,92454,129908,108724,50511,103664,98695,129908,129907,129908,129908,129908,129908,129908
unique,43,119896,37954,425,1229,17,19,15,118781,701,16745,43,5,12,2
top,US,"Gravenstein apple, honeysuckle and jasmine aro...",Reserve,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,Pinot Noir,Wines & Winemakers,US,Americas,Northern America,Developed
freq,54504,3,2006,36247,4480,11065,25512,25512,11,13269,222,54504,63280,54761,119736